name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Create google-service
      run: echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > ./app/google-services.json

    - name: Create Local Properties
      run: echo '${{ secrets.LOCAL_PROPERTIES }}' > ./local.properties
      
    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Run unit tests
      run: ./gradlew testDebugUnitTest
