name: Android CD

on:
  push:
    branches: [ "release" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Firebase CLI
        uses: pocket-apps/action-setup-firebase@v2
        with:
          # Firebase token you can get by running `firebase login:ci`
          firebase-token: ${{secrets.FIREBASE_TOKEN}}

      - name: Create google-services.json
        run: echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > ./app/google-services.json

      - name: Add Naver Map Key into local properties
        env:
            NAVER_MAP_CLIENT_ID: ${{ secrets.NAVER_MAP_CLIENT_ID }}
        run: echo NAVER_MAP_CLIENT_ID="$NAVER_MAP_CLIENT_ID" > ./local.properties

      - name: Add Kakao Rest Api Key into local properties
        env:
          KAKAO_REST_API_KEY: ${{ secrets.KAKAO_REST_API_KEY }}
        run: echo KAKAO_REST_API_KEY="$KAKAO_REST_API_KEY" >> ./local.properties

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: build release
        run: ./gradlew assembleRelease

      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.4.0
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: mogle-testers
          file: app/build/outputs/apk/release/app-release-unsigned.apk

      - name: action-slack
        uses: 8398a7/action-slack@v3.14.0
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
